In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/part_B/imputed_partb.csv")

In [3]:
df = df.drop(["Unnamed: 0","Rndrng_NPI"],axis=1)

In [4]:
df

Rndrng_Prvdr_Crdntls  Rndrng_Prvdr_Gndr  Rndrng_Prvdr_Type  \
0                        7310                0.0                 39   
1                        7310                0.0                 65   
2                        7310                0.0                  5   
3                        7310                1.0                 56   
4                        9043                0.0                 27   
...                       ...                ...                ...   
1100721                  7310                0.0                 22   
1100722                  7310                1.0                 39   
1100723                  3073                0.0                 13   
1100724                  7310                0.0                 63   
1100725                 17582                1.0                 39   

         Rndrng_Prvdr_Mdcr_Prtcptg_Ind  Tot_HCPCS_Cds  Tot_Benes  Tot_Srvcs  \
0                                    1           16.0      291.0      764.0   
1                                    1           18.0     2633.0     5930.0   
2                                    1           54.0      167.0     2003.0   
3                                    1           21.0       56.0      571.0   
4                                    1           30.0       89.0      125.0   
...                                ...            ...        ...        ...   
1100721                              1            9.0      155.0      171.0   
1100722                              1           40.0      333.0     1093.0   
1100723                              1            2.0       66.0      415.0   
1100724                              1           46.0      456.0      851.0   
1100725                              1           15.0      407.0      884.0   

         Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  ...  \
0             402812.00            85319.63           69175.78  ...   
1             915291.00           227372.53          176497.74  ...   
2             182532.48           101757.15           76938.82  ...   
3              23680.00             9011.99            7224.35  ...   
4             152154.00            30631.10           23962.85  ...   
...                 ...                 ...                ...  ...   
1100721       329504.00            32266.94           25803.90  ...   
1100722       182515.00            93505.14           68252.03  ...   
1100723        20985.00            16171.02           11759.42  ...   
1100724       304460.56           113283.09           85463.83  ...   
1100725       340479.02            90924.61           74063.76  ...   

         Bene_CC_Hyplpdma_Pct  Bene_CC_Hyprtnsn_Pct  Bene_CC_IHD_Pct  \
0                        73.0                  75.0             66.0   
1                        48.0                  48.0             24.0   
2                        52.0                  68.0             31.0   
3                        52.0                  50.0             23.0   
4                        43.0                  60.0             33.0   
...                       ...                   ...              ...   
1100721                  71.0                  75.0             70.0   
1100722                  49.0                  66.0             25.0   
1100723                  61.0                  53.0             26.0   
1100724                  44.0                  53.0             26.0   
1100725                  75.0                  75.0             61.0   

         Bene_CC_Opo_Pct  Bene_CC_RAOA_Pct  Bene_CC_Sz_Pct  Bene_CC_Strok_Pct  \
0                   11.0              51.0             9.0               19.0   
1                   10.0              38.0             1.0                3.0   
2                    6.0              75.0            10.0                5.0   
3                   20.0              32.0             0.0                0.0   
4                   13.0              57.0             7.0                8.0   
...

In [5]:
X = df.drop(['Fraud','FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6445108	total: 586ms	remaining: 4m 52s
1:	learn: 0.6004531	total: 973ms	remaining: 4m 2s
2:	learn: 0.5603719	total: 1.39s	remaining: 3m 50s
3:	learn: 0.5237986	total: 1.77s	remaining: 3m 39s
4:	learn: 0.4902815	total: 2.12s	remaining: 3m 29s
5:	learn: 0.4594704	total: 2.58s	remaining: 3m 32s
6:	learn: 0.4310884	total: 2.95s	remaining: 3m 27s
7:	learn: 0.4048528	total: 3.36s	remaining: 3m 26s
8:	learn: 0.3805622	total: 3.72s	remaining: 3m 23s
9:	learn: 0.3580204	total: 4.06s	remaining: 3m 19s
10:	learn: 0.3370901	total: 4.43s	remaining: 3m 16s
11:	learn: 0.3175836	total: 4.77s	remaining: 3m 14s
12:	learn: 0.2993894	total: 5.22s	remaining: 3m 15s
13:	learn: 0.2824223	total: 5.61s	remaining: 3m 14s
14:	learn: 0.2665592	total: 5.96s	remaining: 3m 12s
15:	learn: 0.2516977	total: 6.35s	remaining: 3m 12s
16:	learn: 0.2377840	total: 6.69s	remaining: 3m 9s
17:	learn: 0.2247334	total: 7.04s	remaining: 3m 8s
18:	learn: 0.2124999	total: 7.48s	remaining: 3m 9s
19:	learn: 0.2009982	total

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.9999091511996584

Confusion Matrix:
 [[220126      0]
 [    20      0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    220126
           1       0.00      0.00      0.00        20

    accuracy                           1.00    220146
   macro avg       0.50      0.50      0.50    220146
weighted avg       1.00      1.00      1.00    220146



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [6]:
df = pd.read_csv("../../labelled_data/part_B/partb_rus_features.csv")

In [7]:
df = df.drop(["Unnamed: 0"],axis=1)

In [8]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6858731	total: 105ms	remaining: 52.2s
1:	learn: 0.6782744	total: 161ms	remaining: 40.1s
2:	learn: 0.6708853	total: 199ms	remaining: 33s
3:	learn: 0.6641913	total: 237ms	remaining: 29.4s
4:	learn: 0.6555076	total: 265ms	remaining: 26.3s
5:	learn: 0.6494043	total: 307ms	remaining: 25.2s
6:	learn: 0.6417838	total: 329ms	remaining: 23.2s
7:	learn: 0.6350526	total: 359ms	remaining: 22.1s
8:	learn: 0.6291261	total: 408ms	remaining: 22.3s
9:	learn: 0.6229619	total: 456ms	remaining: 22.3s
10:	learn: 0.6162512	total: 514ms	remaining: 22.9s
11:	learn: 0.6094862	total: 564ms	remaining: 22.9s
12:	learn: 0.6033245	total: 599ms	remaining: 22.4s
13:	learn: 0.5963470	total: 636ms	remaining: 22.1s
14:	learn: 0.5902893	total: 669ms	remaining: 21.6s
15:	learn: 0.5839942	total: 697ms	remaining: 21.1s
16:	learn: 0.5781375	total: 732ms	remaining: 20.8s
17:	learn: 0.5737144	total: 792ms	remaining: 21.2s
18:	learn: 0.5690427	total: 840ms	remaining: 21.3s
19:	learn: 0.5624743	total: 883ms	remaining

In [9]:
df = pd.read_csv("../../labelled_data/part_B/partb_ros_features.csv")

In [10]:
df = df.drop(["Unnamed: 0"],axis=1)

In [11]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6635390	total: 1.37s	remaining: 11m 21s
1:	learn: 0.6362324	total: 2.76s	remaining: 11m 28s
2:	learn: 0.6097057	total: 4.13s	remaining: 11m 24s
3:	learn: 0.5856684	total: 5.46s	remaining: 11m 17s
4:	learn: 0.5635409	total: 6.89s	remaining: 11m 21s
5:	learn: 0.5429654	total: 8.19s	remaining: 11m 14s
6:	learn: 0.5240286	total: 9.49s	remaining: 11m 8s
7:	learn: 0.5039900	total: 10.8s	remaining: 11m 4s
8:	learn: 0.4865123	total: 12.1s	remaining: 10m 58s
9:	learn: 0.4699026	total: 13.3s	remaining: 10m 53s
10:	learn: 0.4546605	total: 14.7s	remaining: 10m 52s
11:	learn: 0.4395168	total: 15.9s	remaining: 10m 47s
12:	learn: 0.4248444	total: 17.2s	remaining: 10m 44s
13:	learn: 0.4097879	total: 18.5s	remaining: 10m 41s
14:	learn: 0.3972168	total: 19.7s	remaining: 10m 37s
15:	learn: 0.3860643	total: 21s	remaining: 10m 36s
16:	learn: 0.3735463	total: 22.4s	remaining: 10m 35s
17:	learn: 0.3626699	total: 23.6s	remaining: 10m 33s
18:	learn: 0.3520763	total: 24.9s	remaining: 10m 30s
19:	lea

In [12]:
df = pd.read_csv("../../labelled_data/part_B/partb_smote_features.csv")

In [13]:
df = df.drop(["Unnamed: 0"],axis=1)

In [14]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6610938	total: 1.64s	remaining: 13m 36s
1:	learn: 0.6315387	total: 3.19s	remaining: 13m 15s
2:	learn: 0.6041818	total: 4.66s	remaining: 12m 51s
3:	learn: 0.5791546	total: 6.06s	remaining: 12m 31s
4:	learn: 0.5559423	total: 7.37s	remaining: 12m 9s
5:	learn: 0.5339632	total: 8.76s	remaining: 12m 1s
6:	learn: 0.5137870	total: 10s	remaining: 11m 47s
7:	learn: 0.4954840	total: 11.4s	remaining: 11m 42s
8:	learn: 0.4782604	total: 12.7s	remaining: 11m 34s
9:	learn: 0.4625307	total: 14s	remaining: 11m 25s
10:	learn: 0.4474893	total: 15.4s	remaining: 11m 25s
11:	learn: 0.4327471	total: 16.9s	remaining: 11m 26s
12:	learn: 0.4193372	total: 18.3s	remaining: 11m 25s
13:	learn: 0.4069284	total: 19.6s	remaining: 11m 20s
14:	learn: 0.3943851	total: 21s	remaining: 11m 18s
15:	learn: 0.3829904	total: 22.4s	remaining: 11m 17s
16:	learn: 0.3719237	total: 23.8s	remaining: 11m 14s
17:	learn: 0.3614749	total: 25.2s	remaining: 11m 14s
18:	learn: 0.3518961	total: 26.5s	remaining: 11m 11s
19:	learn: 

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
df = pd.read_csv("../../labelled_data/part_B/imputed_partb.csv")

In [5]:
df = df.drop(["Unnamed: 0","Rndrng_NPI"],axis=1)

In [6]:
X = df.drop(['Fraud','FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 1.9881597	total: 2.62s	remaining: 10.5s
1:	learn: 1.6827930	total: 4.76s	remaining: 7.14s
2:	learn: 1.4699541	total: 6.85s	remaining: 4.57s
3:	learn: 1.3073201	total: 9.05s	remaining: 2.26s
4:	learn: 1.1762693	total: 11.3s	remaining: 0us
Accuracy: 0.9999091511996584

Confusion Matrix:
 [[220126      0      0      0      0      0]
 [     7      0      0      0      0      0]
 [     2      0      0      0      0      0]
 [     2      0      0      0      0      0]
 [     2      0      0      0      0      0]
 [     7      0      0      0      0      0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    220126
           1       0.00      0.00      0.00         7
           2       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         2
          10       0.00      0.00      0.00         7

    accuracy               

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [7]:
df = pd.read_csv("../../labelled_data/part_B/partb_rus_type_features.csv")

In [8]:
df = df.drop(["Unnamed: 0"],axis=1)

In [9]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 2.2884855	total: 1.03ms	remaining: 512ms
1:	learn: 2.2756067	total: 2.06ms	remaining: 512ms
2:	learn: 2.2631776	total: 2.43ms	remaining: 403ms
3:	learn: 2.2499854	total: 2.92ms	remaining: 362ms
4:	learn: 2.2372687	total: 3.79ms	remaining: 375ms
5:	learn: 2.2242084	total: 4.26ms	remaining: 351ms
6:	learn: 2.2107918	total: 5.13ms	remaining: 361ms
7:	learn: 2.1974215	total: 6.03ms	remaining: 371ms
8:	learn: 2.1841101	total: 6.75ms	remaining: 368ms
9:	learn: 2.1726469	total: 7.26ms	remaining: 356ms
10:	learn: 2.1601569	total: 7.71ms	remaining: 343ms
11:	learn: 2.1495460	total: 8.02ms	remaining: 326ms
12:	learn: 2.1368111	total: 8.97ms	remaining: 336ms
13:	learn: 2.1245084	total: 9.61ms	remaining: 334ms
14:	learn: 2.1114800	total: 10.4ms	remaining: 336ms
15:	learn: 2.1003152	total: 11ms	remaining: 334ms
16:	learn: 2.0880908	total: 11.5ms	remaining: 328ms
17:	learn: 2.0777072	total: 11.9ms	remaining: 319ms
18:	learn: 2.0673476	total: 12.2ms	remaining: 310ms
19:	learn: 2.0556870	tot

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modi

In [10]:
df = pd.read_csv("../../labelled_data/part_B/partb_ros_type_features.csv")

In [11]:
df = df.drop(["Unnamed: 0"],axis=1)

In [12]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 2.1477758	total: 47.5s	remaining: 3m 10s
1:	learn: 1.8879675	total: 2m 10s	remaining: 3m 15s
2:	learn: 1.6934506	total: 3m 42s	remaining: 2m 28s
3:	learn: 1.5446041	total: 5m 9s	remaining: 1m 17s
4:	learn: 1.4229324	total: 6m 41s	remaining: 0us
Accuracy: 0.9273532230029081

Confusion Matrix:
 [[109704  21548  16259     26    619  15017    164  16668   2911      8
   22917  14294    371]
 [     0 190482  14716      0      0      0      0   7500      0      0
       0   7225      0]
 [     0  17089 203071      0      0      0      0      0      0      0
       0      0      0]
 [     0      0      0 219441      0      0      0      0      0      0
       0      0      0]
 [     0      0      0      0 219881      0      0      0      0      0
       0      0      0]
 [     0      0      0      0      0 220554      0      0      0      0
       0      0      0]
 [     0      0      0      0      0      0 220506      0      0      0
       0      0      0]
 [     0      0      0  

: 